[tool.ruff]
line-length = 100
target-version = "py313"
extend-select = ["I", "UP"]

[tool.mypy]
python_version = "3.13"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_untyped_defs = false
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "-q"
pythonpath = ["backend/app"]
