services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: pao
      POSTGRES_PASSWORD: pao
      POSTGRES_DB: pao
      TZ: America/Sao_Paulo
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pao -d pao"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
