name: ci
on:
  push:
    branches: [ "main" ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install deps (backend)
        run: |
          python -m pip install -U pip
          pip install -r backend/requirements.txt -r backend/requirements-dev.txt
      - name: Lint/Type/Test
        run: |
          ruff check .
          mypy backend/app || true
          pytest backend/app/tests -q
